name: gh_sync_workflow

description: "Run after new repository is created under NOAA-GFDL organization. "
branding:
   icon: 'check-circle'
   color: 'blue'

on:
  repository_dispatch

runs:
   using: "docker"
   image: "Dockerfile"

