on: [workflow_dispatch]

jobs:
  gh_sync:
    runs-on: ubuntu-latest
    name: Initiate Sync Process
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build container and execute script
        uses: ./ # Uses an action in the root directory
        
